# Generated by Django 6.0.4 on 2026-05-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.CharField(blank=True, max_length=255)),
                ('company_contact', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('weekly_log_deadline_day', models.PositiveSmallIntegerField(default=4, help_text='Day of week the next log is due (0=Mon..6=Sun). Used to compute submission_deadline server-side.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
