# Generated by Django 6.0.4 on 2026-05-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipplacement',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
