# Generated by Django 5.2.6 on 2026-06-07 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_alter_internshipplacement_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshipplacement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='academic_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements_as_academic_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='workplace_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements_as_workplace_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internshipplacement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='internshipplacement',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
