# Generated by Django 6.0.4 on 2026-05-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('activities', models.TextField()),
                ('challenges', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('submission_deadline', models.DateField(help_text='Computed from placement.weekly_log_deadline_day; not user-set.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('review_feedback', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('revision_request', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-week_number', '-created_at'],
            },
        ),
    ]
