# Generated by Django 6.0.4 on 2026-05-03 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to='placements.internshipplacement'),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='weeklylog',
            index=models.Index(fields=['status', 'submission_deadline'], name='logs_weekly_status_e192db_idx'),
        ),
        migrations.AddConstraint(
            model_name='weeklylog',
            constraint=models.UniqueConstraint(fields=('student', 'week_number'), name='unique_student_week'),
        ),
        migrations.AddConstraint(
            model_name='weeklylog',
            constraint=models.CheckConstraint(condition=models.Q(('week_end__gte', models.F('week_start'))), name='weeklylog_end_after_start'),
        ),
    ]
