# Generated by Django 5.2.6 on 2026-06-07 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_weeklylog_rejected_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklylog',
            name='feedback',
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='review_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='revision_request',
            field=models.TextField(blank=True),
        ),
    ]
